apiVersion: vmoperator.vmware.com/v1alpha1
kind: VirtualMachineClass
metadata:
  name: best-effort-keswick-small
  # No resource requests/reservations.
  # Memory overcommit possible.
spec:
  hardware:
    cpus: 1 
    memory: 1Gi
